"""
Visualization Output Validation Module

Validates that visualization outputs meet schema requirements and
quality standards for User Story 4 (GIS Visualization & Reporting).

Validates:
- File existence and format
- Output dimensions and resolution
- Schema compliance per contracts/output.schema.yaml
- Metadata completeness
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, field

from src.config.constants import VALIDATION_SCHEMA_PATH
from src.config.schemas import validate_against_schema


@dataclass
class ValidationResult:
    """Result of a validation check."""
    is_valid: bool
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class VisualizationOutput:
    """Represents a visualization output to be validated."""
    file_path: str
    file_type: str  # 'png', 'pdf', 'svg', 'geojson', 'kml'
    dimensions: Optional[Tuple[int, int]] = None
    metadata: Optional[Dict[str, Any]] = None
    generation_time: Optional[float] = None
    
class VisualizationValidator:
    """
    Validator for visualization outputs generated by the visualization service.
    
    Ensures outputs meet schema requirements and quality standards before
    being included in reports or shared with stakeholders.
    """
    
    # Required fields in visualization metadata
    REQUIRED_METADATA_FIELDS = [
        'title',
        'description',
        'generated_at',
        'data_sources',
        'visualization_type',
        'spatial_reference'
    ]
    
    # Allowed file types for visualizations
    ALLOWED_FILE_TYPES = ['png', 'pdf', 'svg', 'geojson', 'kml', 'json']
    
    # Minimum recommended dimensions for publication-quality outputs
    MIN_DIMENSIONS = {
        'png': (800, 600),
        'pdf': (612, 792),  # Letter size minimum
        'svg': (400, 300)
    }
    
    # Maximum file size (100MB)
    MAX_FILE_SIZE_BYTES = 100 * 1024 * 1024
    
    def __init__(self, schema_path: Optional[str] = None):
        """
        Initialize the visualization validator.
        
        Args:
            schema_path: Path to the output schema file. Defaults to
                        VALIDATION_SCHEMA_PATH from constants.
        """
        self.schema_path = schema_path or VALIDATION_SCHEMA_PATH
        self._schema = self._load_schema()
    
    def _load_schema(self) -> Optional[Dict]:
        """Load the visualization output schema."""
        try:
            if os.path.exists(self.schema_path):
                with open(self.schema_path, 'r') as f:
                    return json.load(f)
        except Exception:
            pass
        return None
    
    def validate_visualization_output(
        self,
        output: VisualizationOutput,
        strict_mode: bool = True
    ) -> ValidationResult:
        """
        Validate a single visualization output.
        
        Args:
            output: The VisualizationOutput to validate
            strict_mode: If True, warnings become errors
        
        Returns:
            ValidationResult with validation status and details
        """
        result = ValidationResult(is_valid=True)
        
        # Check file existence
        if not self._validate_file_exists(output.file_path, result):
            result.is_valid = False
            return result
        
        # Check file type
        if not self._validate_file_type(output.file_type, result):
            result.is_valid = False
        
        # Check file size
        if not self._validate_file_size(output.file_path, result):
            result.is_valid = False
        
        # Check dimensions
        if output.dimensions:
            if not self._validate_dimensions(
                output.file_type, output.dimensions, result, strict_mode
            ):
                if strict_mode:
                    result.is_valid = False
        
        # Check metadata
        if output.metadata:
            if not self._validate_metadata(output.metadata, result, strict_mode):
                if strict_mode:
                    result.is_valid = False
        
        # Schema validation if schema is available
        if self._schema:
            if not self._validate_against_schema(output, result, strict_mode):
                if strict_mode:
                    result.is_valid = False
        
        return result
    
    def validate_visualization_outputs(
        self,
        outputs: List[VisualizationOutput],
        strict_mode: bool = True
    ) -> Dict[str, ValidationResult]:
        """
        Validate multiple visualization outputs.
        
        Args:
            outputs: List of VisualizationOutput objects to validate
            strict_mode: If True, warnings become errors
        
        Returns:
            Dict mapping file paths to ValidationResult objects
        """
        results = {}
        for output in outputs:
            results[output.file_path] = self.validate_visualization_output(
                output, strict_mode
            )
        return results
    
    def _validate_file_exists(
        self,
        file_path: str,
        result: ValidationResult
    ) -> bool:
        """Validate that the output file exists."""
        if not os.path.exists(file_path):
            error = f"Output file does not exist: {file_path}"
            result.errors.append(error)
            return False
        return True
    
    def _validate_file_type(
        self,
        file_type: str,
        result: ValidationResult
    ) -> bool:
        """Validate that the file type is allowed."""
        if file_type.lower() not in self.ALLOWED_FILE_TYPES:
            error = f"Invalid file type: {file_type}. Allowed: {self.ALLOWED_FILE_TYPES}"
            result.errors.append(error)
            return False
        return True
    
    def _validate_file_size(
        self,
        file_path: str,
        result: ValidationResult
    ) -> bool:
        """Validate that the file size is within limits."""
        try:
            file_size = os.path.getsize(file_path)
            if file_size > self.MAX_FILE_SIZE_BYTES:
                error = f"File size {file_size} bytes exceeds maximum {self.MAX_FILE_SIZE_BYTES} bytes"
                result.errors.append(error)
                return False
            result.metadata['file_size_bytes'] = file_size
        except Exception as e:
            result.warnings.append(f"Could not determine file size: {str(e)}")
        return True
    
    def _validate_dimensions(
        self,
        file_type: str,
        dimensions: Tuple[int, int],
        result: ValidationResult,
        strict_mode: bool
    ) -> bool:
        """Validate that dimensions meet minimum requirements."""
        if file_type.lower() in self.MIN_DIMENSIONS:
            min_width, min_height = self.MIN_DIMENSIONS[file_type.lower()]
            width, height = dimensions
            
            if width < min_width or height < min_height:
                error = (
                    f"Dimensions {dimensions} below minimum {self.MIN_DIMENSIONS[file_type.lower()]} "
                    f"for {file_type}"
                )
                if strict_mode:
                    result.errors.append(error)
                    return False
                else:
                    result.warnings.append(error)
        
        result.metadata['dimensions'] = dimensions
        return True
    
    def _validate_metadata(
        self,
        metadata: Dict[str, Any],
        result: ValidationResult,
        strict_mode: bool
    ) -> bool:
        """Validate that required metadata fields are present."""
        missing_fields = []
        for field_name in self.REQUIRED_METADATA_FIELDS:
            if field_name not in metadata or metadata[field_name] is None:
                missing_fields.append(field_name)
        
        if missing_fields:
            error = f"Missing required metadata fields: {missing_fields}"
            if strict_mode:
                result.errors.append(error)
                return False
            else:
                result.warnings.append(error)
        
        result.metadata['metadata_fields'] = list(metadata.keys())
        return True
    
    def _validate_against_schema(
        self,
        output: VisualizationOutput,
        result: ValidationResult,
        strict_mode: bool
    ) -> bool:
        """Validate output against the loaded schema."""
        try:
            # Build a validation payload from the output
            validation_payload = {
                'file_path': output.file_path,
                'file_type': output.file_type,
                'dimensions': output.dimensions,
                'metadata': output.metadata,
                'generation_time': output.generation_time
            }
            
            # Use the shared schema validation helper
            schema_valid, schema_errors = validate_against_schema(
                validation_payload,
                self._schema
            )
            
            if not schema_valid:
                for error in schema_errors:
                    if strict_mode:
                        result.errors.append(error)
                    else:
                        result.warnings.append(error)
                
                if strict_mode:
                    return False
        except Exception as e:
            result.warnings.append(f"Schema validation error: {str(e)}")
        
        return True
    
    def generate_validation_report(
        self,
        results: Dict[str, ValidationResult]
    ) -> str:
        """
        Generate a human-readable validation report.
        
        Args:
            results: Dict of file paths to ValidationResult objects
        
        Returns:
            Formatted validation report string
        """
        lines = [
            "=" * 60,
            "VISUALIZATION OUTPUT VALIDATION REPORT",
            "=" * 60,
            "",
            f"Total outputs validated: {len(results)}",
            "",
        ]
        
        valid_count = sum(1 for r in results.values() if r.is_valid)
        invalid_count = len(results) - valid_count
        
        lines.append(f"Valid: {valid_count}")
        lines.append(f"Invalid: {invalid_count}")
        lines.append("")
        
        for file_path, result in results.items():
            status = "✓ VALID" if result.is_valid else "✗ INVALID"
            lines.append(f"[{status}] {file_path}")
            
            if result.errors:
                lines.append("  Errors:")
                for error in result.errors:
                    lines.append(f"    - {error}")
            
            if result.warnings:
                lines.append("  Warnings:")
                for warning in result.warnings:
                    lines.append(f"    - {warning}")
            
            lines.append("")
        
        lines.append("=" * 60)
        return "\n".join(lines)

# Convenience functions for common validation patterns
def validate_visualization_file(
    file_path: str,
    file_type: str,
    strict_mode: bool = True
) -> ValidationResult:
    """
    Convenience function to validate a visualization file.
    
    Args:
        file_path: Path to the visualization file
        file_type: Type of visualization (e.g., 'png', 'pdf')
        strict_mode: If True, warnings become errors
    
    Returns:
        ValidationResult object
    """
    validator = VisualizationValidator()
    output = VisualizationOutput(file_path=file_path, file_type=file_type)
    return validator.validate_visualization_output(output, strict_mode)

def validate_visualization_directory(
    directory_path: str,
    strict_mode: bool = True
) -> Dict[str, ValidationResult]:
    """
    Validate all visualization files in a directory.
    
    Args:
        directory_path: Path to the directory containing visualizations
        strict_mode: If True, warnings become errors
    
    Returns:
        Dict mapping file paths to ValidationResult objects
    """
    validator = VisualizationValidator()
    outputs = []
    
    for filename in os.listdir(directory_path):
        file_path = os.path.join(directory_path, filename)
        if os.path.isfile(file_path):
            file_type = filename.split('.')[-1].lower()
            if file_type in validator.ALLOWED_FILE_TYPES:
                outputs.append(VisualizationOutput(
                    file_path=file_path,
                    file_type=file_type
                ))
    
    return validator.validate_visualization_outputs(outputs, strict_mode)
