"""
Create data directory structure for the Bayesian Nonparametrics Anomaly Detection project.

This script creates the required data directories:
- data/raw/: Raw downloaded datasets (never modified)
- data/processed/: Processed/prepared datasets for modeling
- data/interim/: Intermediate data files during processing

Per Constitution Principle III, all data artifacts must be checksummed
and recorded in state/projects/PROJ-024-bayesian-nonparametrics-for-anomaly-dete.yaml
"""
import os
import sys
from pathlib import Path
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def create_data_directories(project_root: Path) -> bool:
    """
    Create the required data directory structure.

    Args:
        project_root: Path to the project root directory

    Returns:
        True if all directories created successfully, False otherwise
    """
    data_dir = project_root / 'data'
    raw_dir = data_dir / 'raw'
    processed_dir = data_dir / 'processed'
    interim_dir = data_dir / 'interim'

    directories = [
        (data_dir, "Data root directory"),
        (raw_dir, "Raw downloaded datasets (immutable)"),
        (processed_dir, "Processed/prepared datasets for modeling"),
        (interim_dir, "Intermediate data files during processing"),
    ]

    success = True
    for dir_path, description in directories:
        try:
            dir_path.mkdir(parents=True, exist_ok=True)
            logger.info(f"✓ Created: {dir_path.relative_to(project_root)} - {description}")
        except OSError as e:
            logger.error(f"✗ Failed to create {dir_path}: {e}")
            success = False

    # Create README files for each directory
    readme_content = {
        'raw': """# Raw Data Directory

This directory contains raw downloaded datasets from external sources.

## Rules:
1. **NEVER modify files in this directory** - raw data must be immutable
2. All files must have SHA256 checksums recorded in state/projects/PROJ-024-bayesian-nonparametrics-for-anomaly-dete.yaml
3. File downloads must be reproducible (same URL, same checksum)

## Expected Contents:
- UCI Electricity dataset (electricity.csv)
- UCI Traffic dataset (traffic.csv)
- UCI Synthetic Control Chart dataset (synthetic_control.csv)
- NAB benchmark datasets (if used)

## Checksums:
Run `python code/scripts/generate_checksums.py` after downloading datasets.
""",
        'processed': """# Processed Data Directory

This directory contains preprocessed datasets ready for model training and evaluation.

## Contents:
- Normalized time series data
- Train/test splits with temporal ordering
- Feature-engineered datasets
- Model input/output artifacts

## Generation:
Processed files are generated by:
- code/scripts/download_datasets.py (initial preprocessing)
- code/scripts/create_train_test_split.py (temporal splits)
- code/scripts/feature_engineering.py (feature creation)

All processed files should reference their raw data source and include
provenance documentation.
""",
        'interim': """# Interim Data Directory

This directory contains temporary data files used during processing pipelines.

## Purpose:
- Intermediate computation results
- Cache files for expensive operations
- Temporary files during batch processing

## Cleanup:
Interim files may be deleted after pipeline completion. Do not commit
interim files to version control (see .gitignore).

## Checksums:
Interim files do NOT require checksums in state file - they are
reproducible from raw/processed data.
"""
    }

    for dir_path, readme in readme_content.items():
        readme_path = project_root / 'data' / dir_path / 'README.md'
        try:
            readme_path.write_text(readme)
            logger.info(f"✓ Created: {readme_path.relative_to(project_root)}")
        except OSError as e:
            logger.error(f"✗ Failed to create {readme_path}: {e}")
            success = False

    return success

def main():
    """Main entry point for data directory creation."""
    # Determine project root (parent of code/scripts)
    script_path = Path(__file__).resolve()
    project_root = script_path.parent.parent.parent

    logger.info(f"Project root: {project_root}")

    if create_data_directories(project_root):
        logger.info("✓ Data directory structure created successfully")
        print("SUCCESS: Data directories created")
        return 0
    else:
        logger.error("✗ Data directory creation failed")
        print("FAILURE: Data directory creation failed")
        return 1

if __name__ == '__main__':
    sys.exit(main())
    execute: true
    timeout_s: 60