#!/usr/bin/env python3
"""Backfill the `submitter:` field on legacy projects/<id>/idea/*.md.

Walks all GitHub issues in ContextLab/llmXive, extracts the model
attribution comment (look for "## 🤖 Model Attribution" or
"BRAINSTORM_IDEA" + bold model name), and matches each issue's title
to a project on disk via case-insensitive substring fuzzy match. For
each match, rewrites the `submitter:` line in the idea Markdown front
matter from `legacy:llmxive-automation` to the actual model name.

Idempotent: safe to re-run; existing non-legacy submitters are kept.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Iterable

import yaml


def gh_issues() -> list[dict]:
    """Pull all issues with comments."""
    res = subprocess.run(
        [
            "gh", "issue", "list", "--repo", "ContextLab/llmXive",
            "--state", "all", "--limit", "300",
            "--json", "number,title,body,comments",
        ],
        check=True, capture_output=True, text=True,
    )
    return json.loads(res.stdout)


def extract_model(comment_body: str) -> str | None:
    """Find the **model-name** line in a model-attribution comment."""
    if "## 🤖 Model Attribution" not in comment_body and "BRAINSTORM_IDEA" not in comment_body:
        return None
    for line in comment_body.splitlines():
        if "generated by" in line.lower():
            m = re.search(r"\*\*([^\*]+)\*\*", line)
            if m:
                return m.group(1).strip()
    return None


def normalize(s: str) -> str:
    return re.sub(r"[^a-z0-9 ]+", " ", s.lower())


def find_match(issue_title: str, projects: list[tuple[str, str, Path]]) -> Path | None:
    """Return the idea-file Path whose project title best matches issue_title.

    `projects` is a list of (proj_id, title, idea_path).
    """
    norm_issue = normalize(issue_title)
    issue_words = set(norm_issue.split())
    if not issue_words:
        return None
    best: tuple[float, Path | None] = (0.0, None)
    for _pid, ptitle, ppath in projects:
        norm_proj = normalize(ptitle)
        proj_words = set(norm_proj.split())
        if not proj_words:
            continue
        # Jaccard on word sets — robust to small differences.
        overlap = issue_words & proj_words
        union = issue_words | proj_words
        if not union:
            continue
        score = len(overlap) / len(union)
        if score > best[0]:
            best = (score, ppath)
    if best[0] >= 0.45:
        return best[1]
    return None


def collect_projects(repo: Path) -> list[tuple[str, str, Path]]:
    out: list[tuple[str, str, Path]] = []
    for state_yaml in (repo / "state" / "projects").glob("*.yaml"):
        d = yaml.safe_load(state_yaml.read_text(encoding="utf-8"))
        if not d:
            continue
        pid = d.get("id")
        title = d.get("title", "")
        idea_dir = repo / "projects" / pid / "idea"
        if not idea_dir.is_dir():
            continue
        idea_md = next(iter(idea_dir.glob("*.md")), None)
        if idea_md is None:
            continue
        out.append((pid, title, idea_md))
    return out


def rewrite_submitter(path: Path, model: str, dry_run: bool = False) -> bool:
    """Replace `submitter: legacy:llmxive-automation` with the actual model.

    Returns True if a change was made.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return False
    end = text.find("---", 3)
    if end < 0:
        return False
    front = text[3:end]
    rest = text[end:]
    try:
        meta = yaml.safe_load(front) or {}
    except yaml.YAMLError:
        return False
    cur = str(meta.get("submitter", ""))
    if cur and cur != "legacy:llmxive-automation" and not cur.startswith("system:"):
        return False
    meta["submitter"] = model
    new_front = yaml.safe_dump(meta, sort_keys=False, default_flow_style=False).strip()
    new_text = f"---\n{new_front}\n{rest}"
    if dry_run:
        print(f"[dry-run] would update {path}: submitter={model}")
        return True
    path.write_text(new_text, encoding="utf-8")
    print(f"updated {path}: submitter={model}")
    return True


def main(argv: Iterable[str]) -> int:
    repo = Path(__file__).resolve().parent.parent
    projects = collect_projects(repo)
    print(f"loaded {len(projects)} projects")
    issues = gh_issues()
    print(f"loaded {len(issues)} issues")
    matches = 0
    rewrites = 0
    dry_run = "--dry-run" in argv
    for issue in issues:
        title = issue.get("title", "")
        body = issue.get("body", "") or ""
        model = None
        for c in (issue.get("comments") or []):
            model = extract_model(c.get("body") or "")
            if model:
                break
        if not model:
            # Some issue bodies have inline attribution.
            model = extract_model(body)
        if not model:
            continue
        match = find_match(title, projects)
        if match is None:
            print(f"  no match: #{issue['number']} {title[:60]} (model={model})")
            continue
        matches += 1
        if rewrite_submitter(match, model, dry_run=dry_run):
            rewrites += 1
    print(f"done: matched={matches}, rewrote={rewrites}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
